[package]
name = "logic"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/logic.rs"

[dependencies]
fetch = { path = "../fetch" }
render = { path = "../render" }
syndicated = { path = "../syndicated" }

